---
reload:
  name: Reload
  description: Reload all entities of MQTT Vacuum Camera platform

turn_off:
  target:
    entity:
      domain: camera

turn_on:
  target:
    entity:
      domain: camera

snapshot:
  target:
    entity:
      domain: camera
  fields:
    filename:
      required: true
      example: "config/www/snapshot_.png"
      selector:
        text:

reset_trims:

vacuum_go_to:
  name: Vacuum go to
  description: Go to the specified coordinates
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    x_coord:
      name: X coordinate
      description: x-coordinate
      required: true
      example: 26300
      selector:
        text:
    y_coord:
      name: Y coordinate
      description: y-coordinate
      required: true
      example: 22500
      selector:
        text:
    spot_id:
      name: Spot Id
      description: Rand256 pre-defined point
      required: false
      example: "Somewhere"
      selector:
        text:
