---
reload:
  name: Reload
  description: Reload all entities of MQTT Vacuum Camera platform

turn_off:
  target:
    entity:
      domain: camera

turn_on:
  target:
    entity:
      domain: camera

snapshot:
  target:
    entity:
      domain: camera
  fields:
    filename:
      required: true
      example: "config/www/snapshot_.png"
      selector:
        text:

reset_trims:

vacuum_go_to:
  name: Vacuum go to
  description: Go to the specified coordinates
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    x_coord:
      name: X coordinate
      description: x-coordinate
      required: true
      example: 26300
      selector:
        text:
    y_coord:
      name: Y coordinate
      description: y-coordinate
      required: true
      example: 22500
      selector:
        text:
    spot_id:
      name: Spot Id
      description: Rand256 pre-defined point
      required: false
      example: "Somewhere"
      selector:
        text:

vacuum_clean_zone:
  name: Vacuum clean zone
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    zone:
      name: Zone
      description: Array of zones. Each zone is an array of 4 integer values.
      required: true
      example: "[[23510,25311,25110,26362]]"
      selector:
        object:
    zone_ids:
      name: Zone Ids
      description: Optional Rand256 predefined zone_ids (array of strings)
      required: false
      example: "[\"Bar\", \"Trash Can\"]"
      selector:
        object:
    repeats:
      name: Repeats
      description: Number of cleaning repeats for each zone.
      selector:
        number:
          min: 1
          max: 3
